DROP TABLE IF EXISTS `service_req`;
CREATE TABLE `service_req` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `act_code` varchar(20) DEFAULT NULL,
  `imei` varchar(20) DEFAULT NULL,
  `latitude` varchar(20) DEFAULT NULL,
  `longitude` varchar(20) DEFAULT NULL,
  `passwd` varchar(150) DEFAULT NULL,
  `ext` varchar(20) DEFAULT NULL,
  `brand_id` varchar(20) DEFAULT NULL,
  `branch_id` varchar(20) DEFAULT NULL,
  `camp_code` varchar(20) DEFAULT NULL,
  `acc_type` varchar(20) DEFAULT NULL COMMENT 'THAIID, TRUECARD, MOBILE',
  `acc_value` varchar(150) DEFAULT NULL,
  `rew_code` varchar(20) DEFAULT NULL,
  `earn_point_amt` double(10,2) DEFAULT '0.00',
  `pay_amt` double(10,2) DEFAULT '0.00',
  `pay_curr` varchar(5) DEFAULT NULL COMMENT 'THB',
  `pay_code` varchar(20) DEFAULT NULL,
  `pay_method` varchar(10) DEFAULT NULL COMMENT 'ALIPAY, WALLET',
  `pay_desc` varchar(150) DEFAULT NULL,
  `req_id` varchar(100) DEFAULT NULL,
  `req_status` varchar(20) DEFAULT NULL,
  `req_datetime` date DEFAULT NULL,
  `req_function` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
